version: "3.9"

services:
  linkedin-scraper:
    build: .
    env_file:
      - .env
    environment:
      LINKEDIN_SCRAPER_HEADLESS: "false"
      PORT: 8002
    ports:
      - "8002:8002"
    shm_size: "2gb"
    volumes:
      - chrome-data:/root/.config/chromium
    restart: unless-stopped

volumes:
  chrome-data:
